name: CI build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: PNPM setup
        uses: ./.github/actions/pnpm-setup

      - name: Build
        run: pnpm build
