name: Publish github page

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Preinstall pnpm
        shell: bash
        run: npx i -g pnpm@latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Build
        run: |
          pnpm build
          pnpm dev
          cd dist
          pnpx vite
